version: 2.1

orbs:
  vr: kohirens/version-release@3.1.0

parameters:
  secrets:
    default: kohirens-automation
    description: Secrets context
    type: string
  secrets_docker:
    default: kohirens-automation-dockerhub
    description: Secrets context
    type: string
  secrets_iac_test:
      default: kohirens-iac-test
      description: Secrets context
      type: string
  ssh_finger:
    description: SSH fingerprint.
    type: string
    default: "6a:92:a1:b6:8f:5c:93:7a:cd:63:f1:49:bc:ba:33:80"
  triggered_flow:
    default: "workflow-selector"
    description: Workflow to be executed.
    type: string

jobs:
  run-test:
    docker:
      - image: hashicorp/terraform:1.3.6
        auth:
          username: ${DH_USER}
          password: ${DH_PASS}
    steps:
      - checkout
      - run:
          command: terraform fmt -check -write=false -diff
      - run:
          command: terraform test -junit-xml="terraform-test-results.xml"
      - store_artifacts:
          path: terraform-test-results.xml
      - store_test_results:
          path: terraform-test-results.xml

workflows:
  quality_checks:
    jobs:
      - run-test:
          context:
            - << pipeline.parameters.secrets_docker >>
            - << pipeline.parameters.secrets_iac_test >>
          filters: { branches: { ignore: /main|auto-update-changelog/ } }

  workflow-selector:
    when:
      and:
        - equal: ["workflow-selector", << pipeline.parameters.triggered_flow >>]
        - equal: [ main, << pipeline.git.branch >> ]
    jobs:
        - vr/workflow-selector:
            context: << pipeline.parameters.secrets >>
            ssh_finger: << pipeline.parameters.ssh_finger >>

  publish-changelog:
    when:
      and:
        - equal: ["publish-changelog", << pipeline.parameters.triggered_flow >>]
    jobs:
        - vr/publish-changelog:
            context: << pipeline.parameters.secrets >>
            ssh_finger: << pipeline.parameters.ssh_finger >>

  publish-release-tag:
    when:
      and:
        - equal: ["publish-release-tag", << pipeline.parameters.triggered_flow >>]
    jobs:
        - vr/tag-and-release:
            context: << pipeline.parameters.secrets >>
