formatter: "markdown" # this is required

version: ""

header-from: main.tf
footer-from: ""

recursive:
    enabled: false
    path: modules

content: ""

output:
    file: "README.md"
    mode: inject
    template: |-
        <!-- BEGIN_TF_DOCS -->
        {{ .Content }}
        <!-- END_TF_DOCS -->

sort:
    enabled: true
    by: name
